apiVersion: v2
publisher: radon
name: helloworld
version: 0.0.1
type: VS Code extension
displayName: RADON-h2020 Hello World
title: A Greeting by RADON
description: An example of plugin to be integrate in Che
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/marklawimperial/radon-vt-plugin
category: Other
spec:
  extensions:
    - https://github.com/marklawimperial/radon-vt-plugin/raw/master/radon-vt-plugin.vsix
